project:
  type: website

website:
  title: "Sports Analytics | Milestone Project"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - href: project.qmd
        text: "Multi-Season Overview"
      - href: seasons.qmd
        text: "Seasons Breakdown"
      - href: about.qmd
        text: "About & Methods"
    right:
      - icon: github
        href: https://github.com/BriannaEubank

format:
  html:
    theme: darkly
    smooth-scroll: true
    toc: true
    toc-depth: 3
    code-fold: show
    code-tools: true
    