project:
  type: website

website:
  title: "NCAA Volleyball Project"
  navbar:
    left:
      - text: "Home / Overview"
        href: project.qmd
      - text: "Nebraska vs SMU"
        href: comparison.qmd